---
name: ci

# yamllint disable-line rule:truthy
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nosborn/github-action-markdown-cli@v3.3.0
        name: markdownlint
        with:
          files: .

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: tf fmt check
        run: terraform fmt -check -recursive

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0

      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-slack-of-failure:
    name: Notify Slack Of Failure
    needs: lint
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: send to slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${LINT_RESULT}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          LINT_RESULT: ${{ jobs.lint.result }}
